// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: books.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBook = `-- name: CreateBook :one
INSERT INTO books (isbn, title, author, description, page_count, publication_year)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (isbn)
WHERE isbn IS NOT NULL DO
UPDATE
SET title      = EXCLUDED.title,
    author     = EXCLUDED.author,
    updated_at = now()
RETURNING id, isbn, title, author, description, page_count, publication_year, created_at, updated_at, deleted_at
`

type CreateBookParams struct {
	Isbn            pgtype.Text `json:"isbn"`
	Title           string      `json:"title"`
	Author          string      `json:"author"`
	Description     pgtype.Text `json:"description"`
	PageCount       pgtype.Int4 `json:"page_count"`
	PublicationYear pgtype.Int4 `json:"publication_year"`
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, createBook,
		arg.Isbn,
		arg.Title,
		arg.Author,
		arg.Description,
		arg.PageCount,
		arg.PublicationYear,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Isbn,
		&i.Title,
		&i.Author,
		&i.Description,
		&i.PageCount,
		&i.PublicationYear,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBookByID = `-- name: GetBookByID :one
SELECT id, isbn, title, author, description, page_count, publication_year, created_at, updated_at, deleted_at
FROM books
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetBookByID(ctx context.Context, id int64) (Book, error) {
	row := q.db.QueryRow(ctx, getBookByID, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Isbn,
		&i.Title,
		&i.Author,
		&i.Description,
		&i.PageCount,
		&i.PublicationYear,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listBooks = `-- name: ListBooks :many
SELECT id, isbn, title, author, description, page_count, publication_year, created_at, updated_at, deleted_at
FROM books
WHERE deleted_at IS NULL
ORDER BY title
`

func (q *Queries) ListBooks(ctx context.Context) ([]Book, error) {
	rows, err := q.db.Query(ctx, listBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Isbn,
			&i.Title,
			&i.Author,
			&i.Description,
			&i.PageCount,
			&i.PublicationYear,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchBooks = `-- name: SearchBooks :many
SELECT id, isbn, title, author, description, page_count, publication_year, created_at, updated_at, deleted_at
FROM books
WHERE (title ILIKE '%' || $1 || '%' OR author ILIKE '%' || $1 || '%')
  AND deleted_at IS NULL
LIMIT 10
`

func (q *Queries) SearchBooks(ctx context.Context, query pgtype.Text) ([]Book, error) {
	rows, err := q.db.Query(ctx, searchBooks, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Isbn,
			&i.Title,
			&i.Author,
			&i.Description,
			&i.PageCount,
			&i.PublicationYear,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
