// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Book struct {
	ID              int64              `json:"id"`
	Isbn            pgtype.Text        `json:"isbn"`
	Title           string             `json:"title"`
	Author          string             `json:"author"`
	Description     pgtype.Text        `json:"description"`
	PageCount       pgtype.Int4        `json:"page_count"`
	PublicationYear pgtype.Int4        `json:"publication_year"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type Sku struct {
	ID            int64              `json:"id"`
	Uuid          pgtype.UUID        `json:"uuid"`
	BookID        int64              `json:"book_id"`
	StoreID       int64              `json:"store_id"`
	PriceInKopeks int32              `json:"price_in_kopeks"`
	StockCount    int32              `json:"stock_count"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type Store struct {
	ID        int64              `json:"id"`
	Uuid      pgtype.UUID        `json:"uuid"`
	Name      string             `json:"name"`
	Address   string             `json:"address"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}
