// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AdjustSKUStock(ctx context.Context, arg AdjustSKUStockParams) (Sku, error)
	CreateBook(ctx context.Context, arg CreateBookParams) (Book, error)
	CreateSKU(ctx context.Context, arg CreateSKUParams) (Sku, error)
	CreateStore(ctx context.Context, arg CreateStoreParams) (Store, error)
	GetBookByID(ctx context.Context, id int64) (Book, error)
	GetSKUByBookAndStore(ctx context.Context, arg GetSKUByBookAndStoreParams) (Sku, error)
	GetSKUByUUID(ctx context.Context, uuid pgtype.UUID) (GetSKUByUUIDRow, error)
	GetStoreByUUID(ctx context.Context, uuid pgtype.UUID) (Store, error)
	ListBookAvailability(ctx context.Context, bookID int64) ([]ListBookAvailabilityRow, error)
	ListBooks(ctx context.Context) ([]Book, error)
	ListSKUsInStore(ctx context.Context, storeID int64) ([]ListSKUsInStoreRow, error)
	ListStores(ctx context.Context) ([]Store, error)
	SearchBooks(ctx context.Context, query pgtype.Text) ([]Book, error)
	SoftDeleteStore(ctx context.Context, uuid pgtype.UUID) error
	UpdateSKUPrice(ctx context.Context, arg UpdateSKUPriceParams) (Sku, error)
	UpdateStore(ctx context.Context, arg UpdateStoreParams) (Store, error)
}

var _ Querier = (*Queries)(nil)
