// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stores.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStore = `-- name: CreateStore :one
INSERT INTO stores (name, address)
VALUES ($1, $2)
RETURNING id, uuid, name, address, created_at, updated_at, deleted_at
`

type CreateStoreParams struct {
	Name    string `json:"name"`
	Address string `json:"address"`
}

func (q *Queries) CreateStore(ctx context.Context, arg CreateStoreParams) (Store, error) {
	row := q.db.QueryRow(ctx, createStore, arg.Name, arg.Address)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getStoreByUUID = `-- name: GetStoreByUUID :one
SELECT id, uuid, name, address, created_at, updated_at, deleted_at
FROM stores
WHERE uuid = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetStoreByUUID(ctx context.Context, uuid pgtype.UUID) (Store, error) {
	row := q.db.QueryRow(ctx, getStoreByUUID, uuid)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listStores = `-- name: ListStores :many
SELECT id, uuid, name, address, created_at, updated_at, deleted_at
FROM stores
WHERE deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListStores(ctx context.Context) ([]Store, error) {
	rows, err := q.db.Query(ctx, listStores)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Store
	for rows.Next() {
		var i Store
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Address,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteStore = `-- name: SoftDeleteStore :exec
UPDATE stores
SET deleted_at = now()
WHERE uuid = $1
`

func (q *Queries) SoftDeleteStore(ctx context.Context, uuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteStore, uuid)
	return err
}

const updateStore = `-- name: UpdateStore :one
UPDATE stores
SET name       = $1,
    address    = $2,
    updated_at = now()
WHERE uuid = $3
  AND deleted_at IS NULL
RETURNING id, uuid, name, address, created_at, updated_at, deleted_at
`

type UpdateStoreParams struct {
	Name    string      `json:"name"`
	Address string      `json:"address"`
	Uuid    pgtype.UUID `json:"uuid"`
}

func (q *Queries) UpdateStore(ctx context.Context, arg UpdateStoreParams) (Store, error) {
	row := q.db.QueryRow(ctx, updateStore, arg.Name, arg.Address, arg.Uuid)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
